### ISSUE TITLE
Add questions for ZCE

### ISSUE THREAD

**Issue by lex111** [leightonthomas/symfony3-certification-helper#26]
Hello, awesome work! We do not think of in order to expand and add questions on the exam ZCE? I understand that you have done only for the Symfony, but can be done in this format for the preparation of ZCE?

**Comment by leightonthomas** [comment]
If you're looking for something with more content that has questions for what I think is the ZCE too, check out https://github.com/certificationy/certificationy-cli
It's a similar thing that I was inspired by - finally found the name again after some digging around! 😛

**Comment by lex111** [comment]
It is interesting, and the truth is very similar, well, I understand, thank you.
